### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap-npm-starter#2]
- [x] Better explanation of npm scripts
- [x] Template repo usage, if that happens
- [x] Mentions of including all CSS/JS vs just some
- [x] Code snippets for additional tools
  - [x] PurgeCSS (done in #6)
  - [x] Bootstrap Icons (coming in #17)
  - [x] Stylelint (coming in #18)

**Comment by Johann-S** [comment]
I think the JS part should use a bundler, something like Webpack or Rollup

**Comment by Xzelsius** [comment]
I would appreciate it to have a proper example for webpack 👍

**Comment by mdo** [comment]
Todos from original comment are done, and other comments are covered in another issue.
